#!/usr/bin/bash
cd "$(dirname "$0")"

APP_NAME='firejail-wrapper_'
CONTROL_PATH=$(find ./ -name 'control')
VERS=$(grep 'Version:' $CONTROL_PATH|awk '{print $2}')

echo "Version: $VERS"

mkdir ./$APP_NAME$VERS

if [ -d ./$APP_NAME$VERS ];then
	mv DEBIAN  etc  sandbox ./$APP_NAME$VERS

	dpkg-deb --build ./$APP_NAME$VERS_arch
else
	echo "ERROR: ./$APP_NAME$VERS_arch wasn't found..."
fi
